/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    2: typeof import('./src/components/ApiTest copy 2.vue')['default']
    ApiTest: typeof import('./src/components/ApiTest.vue')['default']
    BCarousel: typeof import('bootstrap-vue-next')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next')['BCarouselSlide']
    copy: typeof import('./src/components/UserList copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForescast: typeof import('./src/components/UserForescast.vue')['default']
    UserList: typeof import('./src/components/UserList.vue')['default']
    UserWeatherForecast: typeof import('./src/components/UserWeatherForecast.vue')['default']
    UserWeatherForescast: typeof import('./src/components/UserWeatherForescast.vue')['default']
    WeatherForecast: typeof import('./src/components/WeatherForecast.vue')['default']
  }
}
